repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v5.0.0
      hooks:
          - id: check-yaml
          - id: check-json
          - id: check-toml
          - id: trailing-whitespace
          - id: end-of-file-fixer
    - repo: https://github.com/python-poetry/poetry
      rev: '1.8.5'
      hooks:
        - id: poetry-check
        - id: poetry-lock
          args: ["--no-update"]
    - repo: local
      hooks:
          - id: isort
            name: "sort imports"
            language: system
            types: [ file, python ]
            entry: isort
          - id: black
            name: "format the code according to pep8 standards"
            language: system
            types: [ file, python ]
            entry: black pyuow/ tests/
          - id: autoflake
            name: "remove unused imports and unused variables"
            language: system
            types: [ file, python ]
            entry: autoflake
          - id: mypy
            language: system
            name: "type annotations check"
            types: [ file, python ]
            entry: mypy .
            pass_filenames: false
