repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
          - id: check-yaml
          - id: check-json
          - id: check-toml
          - id: trailing-whitespace
          - id: end-of-file-fixer
    - repo: https://github.com/python-poetry/poetry
      rev: '1.6.0'
      hooks:
        - id: poetry-check
        - id: poetry-lock
          args: ["--no-update"]
    - repo: local
      hooks:
          - id: isort
            name: "Sort imports"
            language: system
            types: [ file, python ]
            entry: isort
          - id: black
            name: "Format the code according to pep8 standards"
            language: system
            types: [ file, python ]
            entry: black src/ tests/
          - id: autoflake
            name: "Remove unused imports and unused variables"
            language: system
            types: [ file, python ]
            entry: autoflake
          - id: mypy
            language: system
            name: "Type annotations check"
            types: [ file, python ]
            entry: mypy src/
            pass_filenames: false
