name: PyUoW-build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.11" ]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          curl -sSL https://install.python-poetry.org | python -
          poetry env use python && poetry shell && poetry install

      - name: Run checks
        run: |
          chmod +x ./github/scripts/check.sh
          ./github/scripts/check.sh

      - name: Run tests with Pytest
        run: |
          pytest --cov --cov-report term-missing
